apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vote

resources:
- ../../base

images:
- name: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/vote-docker-repo/vote
  newName: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/vote-docker-repo/vote
  newTag: aa413ea72f242b52dfc804068a0d6686140f3591
