apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-project
  namespace: argocd
spec:
  description: Stateless application workloads
  
  sourceRepos:
    - https://github.com/stackcouture/gitops-microservices-platform.git

  destinations:
    - namespace: vote
      server: https://kubernetes.default.svc

    - namespace: monitoring
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist: []
  
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment

    - group: ''
      kind: Service

    - group: ''
      kind: ConfigMap

    - group: ''
      kind: Secret

    - group: ''
      kind: ServiceAccount

    - group: networking.k8s.io
      kind: Ingress
    
    - group: networking.k8s.io
      kind: NetworkPolicy

    - group: gateway.networking.k8s.io
      kind: HTTPRoute

    - group: policy
      kind: PodDisruptionBudget

    - group: autoscaling
      kind: HorizontalPodAutoscaler

    - group: rbac.authorization.k8s.io
      kind: Role

    - group: rbac.authorization.k8s.io
      kind: RoleBinding

    - group: monitoring.coreos.com
      kind: ServiceMonitor

    - group: monitoring.coreos.com
      kind: PrometheusRule

    - group: argoproj.io
      kind: Rollout