apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-environment-label
spec:
  validationFailureAction: Enforce

  rules:
    - name: allowed-environments
      match:
        any:
        - resources:
            kinds:
              - Deployment
              - StatefulSet
              - Service 
              - Ingress
              - ServiceAccount
              - ServiceMonitor
              - AnalysisTemplate
              - HorizontalPodAutoscaler
              - PrometheusRule
              - Ingress
              - ExternalSecret
              - Namespace

      validate:
        message: "environment must be dev, stage, or prod."
        pattern:
          metadata:
            labels:
              environment: "dev|stage|prod"