apiVersion: v1
kind: LimitRange
metadata:
  name: external-secrets-limits
  namespace: external-secrets
spec:
  limits:
    - type: Container

      defaultRequest:
        cpu: 100m
        memory: 128Mi

      default:
        cpu: 250m
        memory: 256Mi

      min:
        cpu: 50m
        memory: 64Mi

      max:
        cpu: "1"
        memory: 1Gi