apiVersion: v1
kind: ResourceQuota
metadata:
  name: external-secrets-quota
  namespace: external-secrets
spec:
  hard:
    requests.cpu: "250m"
    limits.cpu: "500m"

    requests.memory: 512Mi
    limits.memory: 1Gi

    pods: "10"