apiVersion: v1
kind: ResourceQuota
metadata:
  name: vote-quota
  namespace: vote
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "4"

    requests.memory: 4Gi
    limits.memory: 8Gi

    pods: "50"
    services: "20"
    configmaps: "50"
    secrets: "50"