apiVersion: v1
kind: LimitRange
metadata:
  name: falco-limits
  namespace: falco
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    default:
      cpu: 500m
      memory: 512Mi