apiVersion: v1
kind: ResourceQuota
metadata:
  name: falco-quota
  namespace: falco
spec:
  hard:
    requests.cpu: "5"
    limits.cpu: "10"

    requests.memory: 10Gi
    limits.memory: 20Gi
    pods: "20"