grafana:
  enabled: true

  adminPassword: admin123

prometheus:
  prometheusSpec:
    retention: 10d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo

          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: true