apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
- ../../base

images:
- name: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/platform-automation-repo/daily-platform-report
  newName: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/platform-automation-repo/daily-platform-report
  newTag: 9ebc27e241873c1f674a70736e8f0c22bd6231e1
