apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter

  template:
    metadata:
      labels:
        app: redis-exporter

    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.67.0

        env:
        - name: REDIS_ADDR
          value: redis://redis.redis.svc.cluster.local:6379

        ports:
        - containerPort: 9121
          name: metrics

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi