apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring

  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - redis

  selector:
    matchLabels:
      app: redis-exporter

  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics