apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: platform-project

  source:
    repoURL: https://github.com/stackcouture/gitops-microservices-platform.git
    targetRevision: main
    path: platform/velero/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true