apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-project
  namespace: argocd
spec:
  description: Platform Components

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'