apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres

resources:
  - externalsecret.yaml
  - service-headless.yaml
  - service.yaml
  - statefulset.yaml
  - serviceaccount.yaml
  - pdb.yaml
  - postgres-exporter.yaml
  - servicemonitor.yaml