apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: vote-traffic-check
  namespace: vote

spec:
  metrics:
    - name: request-rate
      interval: 30s
      count: 3
      failureLimit: 1

      successCondition: len(result) > 0 && result[0] >= 1

      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

          query: |
            sum(
              rate(
                flask_http_request_total{
                  job="vote-canary"
                }[1m]
              )
            )

    - name: avg-response-time
      interval: 30s
      count: 3
      failureLimit: 1

      successCondition: len(result) > 0 && result[0] < 1

      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

          query: |
            rate(
              flask_http_request_duration_seconds_sum{
                job="vote-canary"
              }[1m]
            )
            /
            rate(
              flask_http_request_duration_seconds_count{
                job="vote-canary"
              }[1m]
            )