apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vote
  namespace: vote
  labels:
    environment: dev
spec:
  replicas: 3
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
  strategy:
    canary:
      stableService: vote-stable 
      canaryService: vote-canary
      
      maxSurge: 1
      maxUnavailable: 0
      abortScaleDownDelaySeconds: 30
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: vote-analysis

        - setWeight: 50
        - pause:
            duration: 30s
        - analysis:
            templates:
              - templateName: vote-analysis

        - setWeight: 100
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        environment: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: vote-sa
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30

      tolerations:
      - key: workload
        operator: Equal
        value: app
        effect: NoSchedule
      
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 2000

        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: vote
          image: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/vote-docker-repo/vote
          imagePullPolicy: IfNotPresent
          
          ports:
            - containerPort: 8080
              name: http

          env:
            - name: PORT
              value: "8080"

            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /livez
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp
              mountPath: /tmp
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - app
                  - key: pool
                    operator: In
                    values:
                      - app
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: vote


      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway

          labelSelector:
            matchLabels:
              app: vote
      
      volumes:
        - name: tmp
          emptyDir: {}
  
