apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: vote-analysis
  namespace: vote
  labels:
    environment: dev

spec:
  metrics:

  # Verify traffic is reaching the application
  - name: traffic
    interval: 30s
    count: 1
    failureLimit: 1

    successCondition: len(result) > 0 && result[0] > 0

    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(
            increase(flask_http_request_total[1m])
          )

  # Verify error rate stays low
  - name: error-rate
    interval: 30s
    count: 1
    failureLimit: 1

    successCondition: len(result) > 0 && result[0] >= 99

    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          (
            sum(
              increase(flask_http_request_total{status="200"}[1m])
            )
            /
            sum(
              increase(flask_http_request_total[1m])
            )
          ) * 100

  # Verify users are actually voting
  - name: business-rate
    interval: 30s
    count: 1
    failureLimit: 1

    successCondition: len(result) > 0 && result[0] >= 1

    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(vote_requests_total)