apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
    environment: dev
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker-sa
      automountServiceAccountToken: false

      tolerations:
      - key: workload
        operator: Equal
        value: app
        effect: NoSchedule

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - image: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/vote-docker-repo/worker:ec28f9e67183b0bb535fd23af4cebc6c3234ede8
        name: worker
        imagePullPolicy: IfNotPresent
      
        env:
        - name: DB_HOST
          value: db.postgres.svc.cluster.local

        - name: POSTGRES_USER
          value: postgres

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - app
                  - key: pool
                    operator: In
                    values:
                      - app

        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: worker

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: worker
      

      volumes:
      - name: tmp
        emptyDir: {}
    