apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: vote
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-cluster-secret-store

  target:
    name: postgres-secret
    
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: db-password