apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin

resources:
  - deployment.yaml
  - namespace.yaml
  - pgadmin-httproute.yaml
  - pgadmin-secret.yaml
  - pgadmin-svc.yaml