apiVersion: v1
kind: Service
metadata:
  name: daily-platform-report-svc
  namespace: automation
  labels:
    app: daily-platform-report
spec:
  selector:
    app: daily-platform-report
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000