apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - security/run-as-non-root.yaml
  - security/privileged.yaml
  - security/privilege-escalation.yaml
  - security/seccomp.yaml
  - security/capabilities.yaml
  - security/verify-signed-images.yaml

  - resources/requests-limits.yaml

  - reliability/probes.yaml

  - images/registries.yaml
  - images/latest-tag.yaml

  - network/default-deny-network-policy.yaml

  - governance/labels.yaml
  - governance/block-default-namespace.yaml

  - ingress/tls.yaml
  - ingress/clusterissuer.yaml

  - platform/pss-restricted.yaml
  - platform/protect-critical-resources.yaml

  - rbac/kyverno-reports-extra.yaml
  - rbac/kyverno-cert-manager-reports.yaml
  - rbac/kyverno-gateway-reports.yaml