apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-run-as-non-root
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Rollout
              namespaces:
                - vote

      validate:
        message: "Containers must run as a non-root user."
        foreach:
          - list: "request.object.spec.template.spec.containers"
            pattern:
              securityContext:
                runAsNonRoot: true