apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-stackcouture-stage
  namespace: nginx-gateway
spec:
  secretName: wildcard-stackcouture-stage-tls

  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer

  dnsNames:
  - stackcouture.online
  - "*.stackcouture.online"