apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-stackcouture-prod
  namespace: nginx-gateway
spec:
  secretName: wildcard-stackcouture-prod-tls

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
  - stackcouture.online
  - "*.stackcouture.online"