apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - certificate.yaml
  #- staging-certificate.yaml
  - httproutes/argocdhttproute.yaml
  - httproutes/prometheushttproute.yaml
  - httproutes/grafanahttproute.yaml
  - httproutes/votehttproute.yaml
  - httproutes/resulthttproute.yaml
  - httproutes/preview-result-httproute.yaml
  - httproutes/argo-rollouts-route.yaml
  - httproutes/kube-cost-route.yaml
  - httproutes/postgres-exporter-route.yaml
  - httproutes/redis-exporter-route.yaml
  - httproutes/vault-route.yaml