apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: vote
            namespace: vote
            path: apps/vote/overlays/dev
          - name: result
            namespace: vote
            path: apps/result/overlays/dev
          - name: worker
            namespace: vote
            path: apps/worker/overlays/dev
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: apps-project
      source:
        repoURL: https://github.com/stackcouture/gitops-microservices-platform.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
