apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - name: postgres
          #   namespace: postgres
          #   path: infrastructure/postgres/overlays/dev
          - name: redis
            namespace: redis
            path: infrastructure/redis/overlays/dev
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: infra-project
      source:
        repoURL: https://github.com/stackcouture/gitops-microservices-platform.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true