apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argo-rollouts.yaml
  - ingress-nginx-namespace.yaml
  - postgres-namespace.yaml
  - redis-namespace.yaml
  - vote-namespace.yaml