apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-platform
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: database
            namespace: postgres
            path: infra/postgres

          - name: redis
            namespace: redis
            path: infra/redis

          - name: result
            namespace: vote
            path: apps/result
            
          - name: vote
            namespace: vote
            path: apps/vote
          
          - name: worker
            namespace: vote
            path: apps/worker
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/stackcouture/gitops-microservices-platform.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true