apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-secrets
            namespace: external-secrets
            path: platform/external-secrets/overlays/dev
  template:
    metadata:
      name: '{{name}}-app'
    spec:
      project: platform-project
      source:
        repoURL: https://github.com/stackcouture/gitops-microservices-platform.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true