apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-gateway-limits
  namespace: nginx-gateway
spec:
  limits:
    - type: Container

      defaultRequest:
        cpu: 100m
        memory: 128Mi

      default:
        cpu: 500m
        memory: 512Mi

      min:
        cpu: 50m
        memory: 64Mi

      max:
        cpu: "2"
        memory: 2Gi