apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation

resources:
  - daily-platform-report/cronjob.yaml
  - daily-platform-report/servicemonitor.yaml
  - daily-platform-report/service.yaml