apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation-sa
  namespace: automation
  annotations:
    iam.gke.io/gcp-service-account: automation-sa@project-18ee516c-a108-431d-a73.iam.gserviceaccount.com