apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-demo

resources:
  - ../../base

images:
  - name: asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/vote-docker-repo/vote
    newTag: f0a0590c6cd8b5460aa81c383cdaa84a15eba9fc
    
patches:
  - path: replica-patch.yaml