apiVersion: v1
kind: ResourceQuota
metadata:
  name: cert-manager-quota
  namespace: cert-manager
spec:
  hard:
    requests.cpu: "250m"
    limits.cpu: "500m"

    requests.memory: 512Mi
    limits.memory: 1Gi

    pods: "15"